# Generated by Django 4.1.4 on 2022-12-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_alter_realtor_email_alter_realtor_hire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realtor',
            name='password',
            field=models.CharField(default='asdhvbsjvsgvcacaequvguv', max_length=50),
        ),
        migrations.AddField(
            model_name='realtor',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
