# Generated by Django 4.1.4 on 2022-12-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_realtor_logged_in_realtor_password_realtor_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
